# Generated by Django 4.2.16 on 2025-01-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_remove_post_likes_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video_file",
            field=models.FileField(default=0, upload_to=""),
            preserve_default=False,
        ),
    ]
