# Generated by Django 4.2.16 on 2025-01-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_post_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="transformed_field",
            field=models.FileField(default=0, upload_to=""),
            preserve_default=False,
        ),
    ]
