# Generated by Django 4.2.16 on 2025-01-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_post_transformed_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="transformed_field",
            new_name="transformed_file",
        ),
    ]
