# Generated by Django 4.2.16 on 2025-01-19 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_rename_transformed_field_post_transformed_file"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="transformed_file",),
    ]
