# Generated by Django 4.2.16 on 2025-01-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_remove_post_transformed_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="length",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
